parent=keycloak.v2
import=common/keycloak

stylesLib=fontawesome/css/all.css

kcHtmlClass=
kcBodyClass=kc-body
kcFormWrapperClass=kc-form-wrapper
kcFormWrapperHeaderClass=kc-form-wrapper-header
kcLoginClass=pf-v5-c-login__main

kcLogoIdP-google=fa-brands fa-google
